### ISSUE TITLE
vmlinux-2.6.32-5-4kc-malta

### ISSUE THREAD

**Issue by glkfc** [N1nEmAn/Sevnup#3]
对于mipsel，下载的是vmlinux-2.6.32-5-4kc-malta
https://github.com/N1nEmAn/Sevnup/blob/23939a75d9397dd5c503ba4c4c1912b5d65f0cef/run.sh#L90

但实际运行的却是vmlinux-3.2.0-4-4kc-malta
https://github.com/N1nEmAn/Sevnup/blob/23939a75d9397dd5c503ba4c4c1912b5d65f0cef/run.sh#L156

**Comment by N1nEmAn** [comment]
> 对于mipsel，下载的是vmlinux-2.6.32-5-4kc-malta
> 
> https://github.com/N1nEmAn/Sevnup/blob/23939a75d9397dd5c503ba4c4c1912b5d65f0cef/run.sh#L90
> 
> 但实际运行的却是vmlinux-3.2.0-4-4kc-malta
> 
> https://github.com/N1nEmAn/Sevnup/blob/23939a75d9397dd5c503ba4c4c1912b5d65f0cef/run.sh#L156

你是对的，我刚修复了这个问题。实际上你可以直接修改脚本而不用提醒我，非常感谢你的issue
