### ISSUE TITLE
Failed to get "write" lock

### ISSUE THREAD

**Issue by iDTer** [N1nEmAn/Sevnup#5]
请问仿真之后怎么退出？我直接把shell关了，再次使用时会报以下错误：
`===============config and run qemu=====================
                                                    
[o] creating /etc/qemu-ifup... and backup existing /etc/qemu-ifup to /etc/qemu-ifup.bak
[+] now qemu-system-armel is running!
[o] in armel, use username 'root' and password 'root' to login.
[o] input:'ifconfig eth0 10.10.10.2/24' to config ip address.
[o] input:'ping 10.10.10.1' to test if the connection is successful.
[o] input:'wget http://10.10.10.1:8000/load_in_mips.sh' to download script.
[o] input:'sh load_in_mips.sh' to finish all the work.
                                                    
qemu-system-arm: -hda ./img/debian_wheezy_armel_standard.qcow2: Failed to get "write" lock
Is another process using the image [./img/debian_wheezy_armel_standard.qcow2]?`

但是使用lsof ./img/debian_wheezy_armel_standard.qcow2命令也看不到正在使用这个文件的进程，也没有在./img下面找到/img/debian_wheezy_armel_standard.qcow2.lock类似的锁文件。

重启可以解决，不过请问还有其他办法吗？谢谢大佬的回复orz

**Comment by N1nEmAn** [comment]
退出的时候直接pkill对应的qemu即可，比如`pkill qemu-arm-static`，估计是被qemu占用了，希望对你有帮助！感谢

**Comment by iDTer** [comment]
好的，谢谢
